# Generated by Django 3.2.23 on 2024-02-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miportafolio',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miportafolio',
            name='tecnologia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='miportafolio',
            name='imagen',
            field=models.ImageField(default='proyecto_img/1654774204073.jpg', upload_to='proyecto_img/'),
        ),
    ]
